[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  PUPPETEER_SKIP_DOWNLOAD = "true"

[functions]
  directory = ".netlify/functions"

[[plugins]]
  package = "netlify-plugin-chromium"