[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  PUPPETEER_SKIP_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/opt/buildhome/.cache/puppeteer/chrome/linux-135.0.7049.42/chrome-linux64/chrome"

[functions]
  directory = ".netlify/functions"

[[plugins]]
  package = "netlify-plugin-chromium"


