[build]
  command = "yarn install --legacy-peer-deps && yarn build"  # Use yarn consistently
  publish = ".next"

[build.environment]
  PUPPETEER_SKIP_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/opt/buildhome/.cache/puppeteer/chrome/linux-135.0.7049.42/chrome-linux64/chrome"

[functions]
  directory = ".netlify/functions"

[[plugins]]
  package = "netlify-plugin-chromium"
  [plugins.inputs]  # Correct way to define inputs
  packageManager = "yarn"  # Ensure this matches your setup (npm or yarn)
  setChromePathInEnv = true  # Set Chrome path automatically in the environment
  failBuildOnError = true